[project]
name = "helloworld-click-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "litellm>=1.65.4.post1",
]
